#!/usr/bin/env bash

set -eu

TEXTFILE=${PROM_FILE_PATH:-/var/lib/node_exporter/textfile_collector/dht11-metrics.prom}
TEMPFILE=$TEXTFILE.$$
SLEEP_DURATION=${SLEEP_DURATION:-15}

export SCRIPT_DIR=${BASH_SOURCE%/*}

trap "rm $TEXTFILE $TEMPFILE" EXIT KILL TERM STOP

while true; do
	mkdir -p $(dirname $TEXTFILE)

	cat /dev/null > $TEMPFILE

	${SCRIPT_DIR}/dht11.py >> $TEMPFILE

	mv $TEMPFILE $TEXTFILE
	sleep $SLEEP_DURATION
done
